Select * from amber_su16 where COURSE_NUMBER = 'EIN5930';
select * from DL_COURSES WHERE COURSE_NUMBER = 'LIS5916';
select * from JANA_PK WHERE program_pk = 644;
select * from DL_PROGRAMS WHERE program_pk = 604;
SELECT * FROM dL_COURSES WHERE COURSE_NUMBER = 'EDF6479';

select * from DL_PROGRAM_COURSE_TERMS WHERE ASSOCIATION_PK = 3780 AND YEAR = '2016';
SELECT * FROM DL_PROGRAMS WHERE PROGRAM_PK = 160;

DELETE FROM DL_PROGRAM_COURSE_TERMS WHERE TERM_PK = 6490;

DELETE FROM dl_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK IN (1841,1900,1898,1899,1838,1842,2319,2598,2985);
DELETE FROM DL_PROGRAM_COURSE_TERMS WHERE ASSOCIATION_PK IN (2010,2030,2143,2145,2223,2224,2225,2689,2741,2742,3085,3775,3782,3792);

SELECT * FROM DL_COURSES WHERE COURSE_NUMBER = 'LIS4930';

SELECT * FROM DL_COURSE_REQUISITES WHERE COURSE_PK = 1462;

/*
<> is !=
*/
DELETE FROM DL_COURSES WHERE COURSE_NUMBER = 'LIS5916'AND COURSE_PK <> 1551;


/* 
remember to write a statement to concatenate the course fee data in the database rather than in excell
*/
select * from carol_su16 where COURSE_NUMBER = 'LAE5867';
SELECT * from DL_COURSES where COURSE_NUMBER = 'LAE5867';
SELECT * from JANA_PK where COURSE_NUMBER = 'LAE5867';
/* REMOVE 3181 */
SELECT * FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK = 3181;
SELECT * FROM DL_PROGRAM_COURSE_TERMS WHERE ASSOCIATION_PK = 4047;

DELETE FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK = 3181;
DELETE FROM DL_COURSES WHERE COURSE_PK = 3181;

/* RENAME COURSE NUMBER FROM LAE */

UPDATE JANA_PK
SET COURSE_NUMBER = 'EDG5867'
WHERE COURSE_NUMBER = 'LAE5867';

SELECT * FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK = 1593;
/* THE FOLLOWING COURSES NEED TO BE ADDED TO 604, THEY HAVE SPECIAL CREDIT HOUR FEES */
SELECT * FROM CAROL_SU16 WHERE COURSE_NUMBER IN ('EEX5087', 'EEX5234', 'EEX5248', 'EEX5704');

SELECT * FROM DL_COURSES WHERE COURSE_NUMBER IN ('EEX5087', 'EEX5234', 'EEX5248', 'EEX5704');
/*
1192
1197
1185
1188
*/

SELECT * FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK IN (1192, 1197, 1185, 1188);

INSERT INTO DL_PROGRAM_COURSE_ASSOCIATION (COURSE_PK, PROGRAM_PK)
  VALUES (3632,145);

SELECT * FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE trunc(last_updated) = '23-MAR-16' AND course_pk = 3632;

INSERT INTO DL_PROGRAM_COURSE_TERMS (ASSOCIATION_PK, TERM_NUMBER, TERM_TEXT, YEAR)
  VALUES (3800,6,'Summer',2016);
/* add space at end to differentiate between the two EIN5930 courses and LIS5916 */
SELECT * FROM DL_COURSES WHERE COURSE_NUMBER = 'EIN5930 ';

SELECT * FROM JANA_PK WHERE COURSE_NUMBER = 'EIN5930';

/* EDIT 2982 WITH SPACE FOR COURSE NUM */
UPDATE DL_COURSES
SET COURSE_description='This course will provide students with a basic knowledge of the prescription and fabrication of various Prosthetic and Orthotic devices using specified medical composite materials.  The lab is designed to encourage students to apply the principles of practical material science to biomechanics, case study, and actual clinical practice.'
WHERE COURSE_PK = 2982;

SELECT * FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK = 2982;

SELECT TUITION_AND_FEES FROM DL_COURSES WHERE TUITION_AND_FEES LIKE '%2015-16%';

UPDATE DL_COURSES
SET TUITION_AND_FEES = REPLACE (TUITION_AND_FEES, '2014-2015', '2015-16');


SELECT * FROM DL_COURSES WHERE COURSE_NUMBER = 'CCJ';

UPDATE DL_COURSES
SET DEPARTMENT_NAME = 'Public Safety and Security'
WHERE COURSE_PK = 3278;

SELECT * FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK = 3278;


SELECT * FROM CHRISTINA_SU16 WHERE COURSE_NUMBER = 'ECO3223'; 
select * from jana_pk where course_number = 'ECO3223'; /* associate pk 3043 */
select * from dl_courses where COURSE_NUMBER = 'ECO3223';

select * from dl_program_course_terms where ASSOCIATION_PK = 3043;

UPDATE DL_COURSES
SET DEPARTMENT_NAME = 'Economics'
WHERE COURSE_PK = 1135;


SELECT COURSE_PK FROM DL_COURSES WHERE COURSE_NUMBER IN ('GIS4006');
select * from dl_course_requisites where course_pk = 1244;

DELETE FROM DL_COURSE_REQUISITES WHERE COURSE_PK = 1244;

SELECT * FROM JANA_PK WHERE COURSE_NUMBER = 'ISS4931';
SELECT * FROM CHRISTINA_SU16 WHERE COURSE_NUMBER = 'ISS4931';

SELECT * FROM DL_PROGRAM_COURSE_ASSOCIATION WHERE COURSE_PK = 3558; /*REPLACE 4945 WITH 4483*/

SELECT * FROM DL_PROGRAM_COURSE_TERMS WHERE ASSOCIATION_PK = 4483;

UPDATE DL_PROGRAM_COURSE_TERMS
SET ASSOCIATION_PK = 4483
WHERE ASSOCIATION_PK = 4945;

DELETE FROM DL_PROGRAM_COURSE_TERMS WHERE TERM_PK = 6201;

SELECT COURSE_PK FROM JANA_PK WHERE COURSE_NUMBER = 'STA2122';

SELECT * FROM DL_COURSE_REQUISITES WHERE COURSE_PK = 3479;

INSERT INTO DL_COURSE_REQUISITES (COURSE_PK, REQ_COURSE_NUMBER, REQ_TYPE)
  VALUES (3479, 'MAC1105','Prerequisite');
  
SELECT * FROM DL_PROGRAMS WHERE PROGRAM_PK = 604;

UPDATE DL_PROGRAMS
SET FEE_TYPE = 'The cost of this program is equal to tuition and fees for the Academic Year 2015-16 as stated on the <a href="http://controller.vpfa.fsu.edu/student-business/tuition" target="_blank">Student Business Services website</a>, plus a $25.00 per credit hour distance learning fee. <a href="mailto:mailto:sdezerga@fsu.edu">Contact the department</a> for more specific fee information relative to student status and location. <br>*Please note the fee for the 4 summer courses  listed is not typical of the $60 per credit hour program fee.  The reduced fee applies only to these courses.'
WHERE PROGRAM_PK = 604;