/*update fees*/
BEGIN
  FOR X IN
    (SELECT COURSE_NUMBER, TUITION_AND_FEES FROM FEES)
      LOOP
        UPDATE DL_COURSES Y
          SET Y.TUITION_AND_FEES = X.TUITION_AND_FEES
            WHERE Y.COURSE_NUMBER = X.COURSE_NUMBER;
      END LOOP;
END; 
/
